name: mojap package dependencies
description: a test that checks package version changes made during mojap package devleopment do not conflict with other mojap package dependencies

inputs:
  repo:
    description: repo calling this action
    required: true
  python-versions:
    description: versions of python to test
    required: true

runs:
  using: composite
  strategy:
    fail-fast: true
    matrix:
      python-version: ${{ inputs.python-versions }}
  steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: strip out calling repo from install string
        id: strip_repo
        run: |
          INSTALLS=$(python .github/scripts/mojap_package_names.py --repo=${{ inputs.repo }})
          echo "::set-output name=INSTALLS::$INSTALLS"
        shell: bash
      - name: check changes for conflicts with other mojap package dependencies
        run: |
          python -m pip install --upgrade pip
          eval ${{ steps.strip_repo.outputs.INSTALLS }}
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
          pip check
        shell: bash
