name: mojap package dependencies
description: a test that checks package version changes made during mojap package devleopment do not conflict with other mojap package dependencies

inputs:
  org-repo:
    description: org and repo calling this action
    required: true
  repo:
    description: repo name calling this action
    required: true
  use-poetry-extras:
    description: whether to use poetry extras in install
    default: false
    required: false
  poetry-install-extras:
    description: extras to pass to poetry install
    default: ""
    required: false

runs:
  using: composite
  steps:
      - name: checkout composite repo
        uses: actions/checkout@v2
        with:
          repository: moj-analytical-services/actions-mojap-package-depends
      - name: strip out calling repo from install string
        id: strip_repo
        run: |
          INSTALLS=$(python mojap_package_names.py --repo=${{ inputs.repo }})
          echo "::set-output name=INSTALLS::$INSTALLS"
        shell: bash
      - name: checkout calling repo
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.org-repo }}
      - name: check changes for conflicts with other mojap package dependencies
        run: |
          python -m pip install --upgrade pip
          eval ${{ steps.strip_repo.outputs.INSTALLS }}
          pip install poetry
          poetry config virtualenvs.create false
          if ${{ inputs.use-poetry-extras }}
          then poetry install --no-root --extras "{{ inputs.poetry-install-extras }}"
          else poetry install --no-root
          fi
          pip check
        shell: bash
